apiVersion: v1
kind: ConfigMap
data:
  glance-registry.conf: |-
    [DEFAULT]
    debug = {{ misc.debug }}
    use_syslog = False
    use_stderr = True

    bind_host = {{ network.ip_address }}
    bind_port = {{ network.port.registry }}

    workers = {{ misc.workers }}

    [database]
    connection = mysql+pymysql://{{ database.glance_user }}:{{ database.glance_password }}@{{ database.address }}/{{ database.glance_database_name }}
    max_pool_size = {{ misc.workers }}
    max_overflow  = {{ misc.workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.glance_user }}
    password = {{ keystone.glance_password }}

    [paste_deploy]
    flavor = keystone

    [oslo_messaging_notifications]
    driver = noop
