apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: glance-glanceregistryconf
data:
  glance-registry.conf: |-
    [DEFAULT]
    debug = {{ debug }}
    use_syslog = False
    use_stderr = True

    bind_host = {{ ip_address }}
    bind_port = {{ registry_port }}

    workers = {{ workers }}

    [database]
    connection = mysql+pymysql://{{ database_glance_user }}:{{ database_glance_password }}@{{ database_address }}/{{ database_glance_name }}
    max_pool_size = {{ workers }}
    max_overflow  = {{ workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone_auth_uri }}
    auth_url = {{ keystone_auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone_glance_user }}
    password = {{ keystone_glance_password }}

    [paste_deploy]
    flavor = keystone

    [oslo_messaging_notifications]
    driver = noop
