apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ variables.deployment.namespace }}
  name: keystone-dbsyncsh
data:
  db-sync.sh: |-
    #!/bin/bash
    set -ex

    keystone-manage db_sync
    kolla_keystone_bootstrap {{ variables.admin_user }} {{ variables.admin_password }} {{ variables.admin_project_name }} admin http://keystone-api:{{ variables.network.port.admin }}/v3 http://keystone-api:{{ variables.network.port.public }}/v3 http://keystone-api:{{ variables.network.port.public }}/v3 {{ variables.admin_region_name }}
