apiVersion: v1
kind: Service
metadata:
  namespace: {{ deployment.namespace }}
  name: rados-gateway
spec:
  sessionAffinity: ClientIP
  externalIPs: {{ network.external_ips }}
  ports:
  - port: {{ network.port }}
  selector:
    app: rados-gateway
