apiVersion: v1
kind: Service
metadata:
  namespace: {{ variables.deployment.namespace }}
  name: rados-gateway
spec:
  sessionAffinity: ClientIP
  externalIPs: {{ variables.network.external_ips }}
  ports:
  - port: {{ variables.network.port }}
  selector:
    app: rados-gateway
