apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ variables.deployment.namespace }}
  name: glance-init
spec:
  template:
    metadata:
      namespace: {{ variables.deployment.namespace }}
      name: glance-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: glance-init
          image: {{ variables.deployment.image.init }}
          imagePullPolicy: Always
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/init.sh"
            - name: DEPENDENCY_SERVICE
              value: "mariadb"
            - name: DEPENDENCY_CONFIG
              value: "/tmp/init.sh"
          volumeMounts:
            - name: initsh
              mountPath: /configmaps/init.sh
      volumes:
        - name: initsh
          configMap:
            name: glance-initsh
