apiVersion: v1
kind: ConfigMap
data:
  start.sh: |-
    #!/bin/bash
    set -ex

    # Copy configuration files.
    cp /configmaps/ceph.conf/ceph.conf /etc/ceph/
    cp /configmaps/ceph.client.admin.keyring/ceph.client.admin.keyring /etc/ceph/

    # TODO(Quentin-M): Hack for missing newlines
    echo "" >> /etc/ceph/ceph.conf
    echo "" >> /etc/ceph/ceph.client.admin.keyring

    # Create initial user.
    radosgw-admin user info --uid={{ rados_gateway.swift_user_uid }}
    if [ $? -gt 0 ]; then
            radosgw-admin user create --uid={{ rados_gateway.swift_user_uid }} --display-name="{{ rados_gateway.swift_user_display_name }}"
            radosgw-admin subuser create --uid={{ rados_gateway.swift_user_uid }} --subuser={{ rados_gateway.swift_user }} --access=full
            radosgw-admin key create --subuser={{ rados_gateway.swift_user }} --key-type=swift --secret={{ rados_gateway.ceph_admin_keyring }}
            radosgw-admin user modify --uid={{ rados_gateway.swift_user_uid }} --temp-url-key=glance_temp_url_key
    fi

    # Export bootstrap-rgw keyring.
    ceph auth get client.bootstrap-rgw -o /var/lib/ceph/bootstrap-rgw/ceph.keyring || exit 1

    # Configure and start Ceph entrypoint.
    export CEPH_DAEMON="rgw"
    export RGW_CIVETWEB_PORT="{{ network.port }}"
    /entrypoint.sh
