apiVersion: v1
kind: Service
metadata:
  namespace: {{ deployment.namespace }}
  name: keystone-api
spec:
  ports:
  - name: keystone-api-public
    port: {{ network.port.public }}
  - name: keystone-api-admin
    port: {{ network.port.admin }}
  selector:
    app: keystone-api
