apiVersion: v1
kind: ConfigMap
data:
  glance-api.conf: |-
    [DEFAULT]
    debug = {{ misc.debug }}
    use_syslog = False
    use_stderr = True

    bind_host = {{ network.ip_address }}
    bind_port = {{ network.port.api }}

    workers = {{ misc.workers }}
    registry_host = glance-registry

    # Enable Copy-on-Write
    show_image_direct_url = True

    [database]
    connection = mysql+pymysql://{{ database.glance_user }}:{{ database.glance_password }}@{{ database.address }}/{{ database.glance_database_name }}
    max_pool_size = {{ misc.workers }}
    max_overflow  = {{ misc.workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.glance_user }}
    password = {{ keystone.glance_password }}

    [paste_deploy]
    flavor = keystone

    [oslo_messaging_notifications]
    driver = noop

    [glance_store]
    filesystem_store_datadir = /var/lib/glance/images/

    {% if not ceph.enabled -%}
    stores = file, http
    default_store = file
    {%- else -%}
    stores = file, http, rbd
    default_store = rbd
    rbd_store_pool = {{ ceph.glance_pool }}
    rbd_store_user = {{ ceph.glance_user }}
    rbd_store_ceph_conf = /etc/ceph/ceph.conf
    rbd_store_chunk_size = 8
    {%- endif -%}
