apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: glance-glanceapiconf
data:
  glance-api.conf: |-
    [DEFAULT]
    debug = {{ debug }}
    use_syslog = False
    use_stderr = True

    bind_host = {{ ip_address }}
    bind_port = {{ api_port }}

    workers = {{ workers }}
    registry_host = glance-registry

    [database]
    connection = mysql+pymysql://{{ database_glance_user }}:{{ database_glance_password }}@{{ database_address }}/{{ database_glance_name }}
    max_pool_size = {{ workers }}
    max_overflow  = {{ workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone_auth_uri }}
    auth_url = {{ keystone_auth_url }}
    auth_type = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone_glance_user }}
    password = {{ keystone_glance_password }}

    [paste_deploy]
    flavor = keystone

    [oslo_messaging_notifications]
    driver = noop

    [glance_store]
    filesystem_store_datadir = /var/lib/glance/images/

    {% if not ceph_enabled -%}
    stores = file, http
    default_store = file
    {%- else -%}
    stores = file, http, swift
    default_store = swift
    swift_store_auth_version = 1
    swift_store_auth_address = {{ ceph_swift_auth }}
    swift_store_user = {{ ceph_swift_user }}
    swift_store_key = {{ ceph_admin_keyring }}
    default_swift_reference = ref1
    swift_store_config_file = /etc/glance/glance-swift-store.conf
    swift_store_container = glance
    swift_store_create_container_on_put = True
    {%- endif -%}
