apiVersion: v1
kind: ConfigMap
metadata:
 namespace: {{ namespace }}
 name: glance-postsh
data:
 post.sh: |-
    #!/bin/bash
    set -ex

    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ region_name }} url='http://glance-api:{{ port }}' interface=admin keystone_region_name={{ keystone_region_name }} auth='{{ keystone_auth }}'" -e "{'openstack_glance_auth':{{ keystone_auth }}}"
    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ region_name }} url='http://glance-api:{{ port }}' interface=internal keystone_region_name={{ keystone_region_name }} auth='{{ keystone_auth }}'" -e "{'openstack_glance_auth':{{ keystone_auth }}}"
    ansible localhost -vvv -m kolla_keystone_service -a "service_name=glance service_type=image description='Openstack Image' endpoint_region={{ region_name }} url='http://glance-api:{{ port }}' interface=public keystone_region_name={{ keystone_region_name }} auth='{{ keystone_auth }}' " -e "{'openstack_glance_auth':{{ keystone_auth }}}"
    ansible localhost -vvv -m kolla_keystone_user -a "project=service user=glance password={{ glance_keystone_password }} role=admin keystone_region_name={{ keystone_region_name }} auth='{{ keystone_auth }}'" -e "{'openstack_glance_auth':{{ keystone_auth }}}"
    ansible localhost -vvv -m kolla_sanity -a "service=glance project=service user=glance password={{ glance_keystone_password }} role=admin keystone_region_name={{ keystone_region_name }} auth={{ keystone_auth }}" -e "{'openstack_glance_auth':{{ keystone_auth }}}"

    ansible localhost -vvv -m mysql_db -a "login_host='{{ database_address }}' login_port='{{ database_port }}' login_user='{{ database_user }}' login_password='{{ database_password }}' name='{{ database_glance_name }}'"
    ansible localhost -vvv -m mysql_user -a "login_host='{{ database_address }}' login_port='{{ database_port }}' login_user='{{ database_user }}' login_password='{{ database_password }}' name='{{ database_glance_user }}' password='{{ database_glance_password }}' host='%' priv='{{ database_glance_name }}.*:ALL' append_privs='yes'"
