apiVersion: v1
kind: ConfigMap
data:
  db-sync.sh: |-
    #!/bin/bash

    # TODO(Quentin-M): Hack for missing newlines
    echo "" >> /etc/ceph/ceph.conf
    echo "" >> /etc/ceph/ceph.client.admin.keyring

    ceph auth get client.{{ rados_gateway.cinder_user }}

    if [ $? -ne 0 ];then
     ceph-authtool -n client.{{ rados_gateway.cinder_user }} --cap osd 'allow class-read object_prefix rbd_children, allow rwx pool={{ rados_gateway.cinder_pool }}, allow rwx pool=cinder-cache, allow rwx pool=nova, allow rwx pool=nova-cache, allow rwx pool=glance, allow rwx' --cap mon 'allow rwx' -C /etc/ceph/ceph.client.cinder.keyring --gen-key

     ceph auth add client.{{ rados_gateway.cinder_user }} -i /etc/ceph/ceph.client.{{ rados_gateway.cinder_user }}.keyring
    fi

    ceph osd pool get {{ rados_gateway.cinder_pool }} size

    if [ $? -ne 0 ];then
      set -e
      ceph osd pool create {{ rados_gateway.cinder_pool }} 1024 1024
    fi

    set -ex
    cinder-manage db sync
