apiVersion: v1
kind: ConfigMap
data:
  nova.conf: |-
    [DEFAULT]
    debug = {{ misc.debug }}
    vif_plugging_is_fatal = False
    vif_plugging_timeout = 1

    api_paste_config = /etc/nova/api-paste.ini
    state_path = /var/lib/nova

    osapi_compute_listen = {{ network.ip_address }}
    osapi_compute_listen_port = {{ network.port.api }}
    osapi_compute_workers = {{ misc.workers }}

    workers = {{ misc.workers }}

    enabled_apis = osapi_compute

    notification_driver = noop

    use_neutron = True
    security_group_api = neutron
    network_api_class = nova.network.neutronv2.api.API
    firewall_driver = nova.virt.firewall.NoopFirewallDriver
    linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver

    allow_resize_to_same_host = true

    compute_driver = libvirt.LibvirtDriver

    # Though my_ip is not used directly, lots of other variables use $my_ip
    my_ip = {{ network.ip_adress }}

    [vnc]
    novncproxy_host = {{ network.ip_address }}
    novncproxy_port = {{ network.port.novncproxy }}
    vncserver_listen = 0.0.0.0
    vncserver_proxyclient_address = {{ network.ipaddress }}
    novncproxy_base_url = http://{{ external_ip }}:6080/vnc_auto.html
    vnc_enabled = True

    [oslo_messaging_rabbit]
    rabbit_userid = {{ rabbitmq.admin_user }}
    rabbit_password = {{ rabbitmq.admin_password }}
    rabbit_ha_queues = true
    rabbit_hosts = {{ rabbitmq.address }}

    [oslo_concurrency]
    lock_path = /var/lib/nova/tmp

    [conductor]
    workers = {{ misc.workers }}

    [glance]
    api_servers = {{ glance.api_url }}
    num_retries = 3

    [cinder]
    catalog_info = volume:cinder:internalURL

    [neutron]
    url = {{ neutron.api_url }}
    auth_strategy = keystone
    metadata_proxy_shared_secret = {{ neutron.metadata_secret }}
    service_metadata_proxy = true

    auth_url = {{ keystone.auth_url }}
    auth_plugin = password
    project_domain_name = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.neutron_user }}
    password = {{ keystone.neutron_password }}

    [database]
    connection = mysql+pymysql://{{ database.nova_user }}:{{ database.nova_password }}@{{ database.address }}/{{ database.nova_database_name }}
    max_pool_size = {{ misc.workers }}
    max_overflow  = {{ misc.workers }}

    [api_database]
    connection = mysql+pymysql://{{ database.nova_user }}:{{ database.nova_password }}@{{ database.address }}/{{ database.nova_api_database_name }}
    max_pool_size = {{ misc.workers }}
    max_overflow  = {{ misc.workers }}

    [keystone_authtoken]
    auth_uri = {{ keystone.auth_uri }}
    auth_url = {{ keystone.auth_url }}
    auth_plugin = password
    project_domain_id = default
    user_domain_id = default
    project_name = service
    username = {{ keystone.nova_user }}
    password = {{ keystone.nova_password }}

    [libvirt]
    connection_uri = "qemu+tcp://{{ network.ip_address }}/system"

    {% if rados_gateway.enabled %}
    images_type = rbd
    images_rbd_pool = {{ rados_gateway.nova_pool }}
    images_rbd_ceph_conf = /etc/ceph/ceph.conf
    rbd_user = {{ rados_gateway.cinder_user }}
    rbd_secret_uuid = {{ rados_gateway.secret_uuid }}
    disk_cachemodes="network=writeback"
    hw_disk_discard = unmap
    {% endif %}

    [upgrade_levels]
    compute = auto

    [serial_console]
    enabled = False
