apiVersion: v1
kind: ConfigMap
data:
  virsh-set-secret.sh: |-
    #!/bin/bash
    set -ex

    sleep 10

    KEY=$(ceph auth get-key client.{{ rados_gateway.cinder_user }})
    virsh secret-define --file /tmp/secret.xml
    virsh secret-set-value --secret {{ rados_gateway.secret_uuid }} --base64 $KEY && rm /tmp/secret.xml
