apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ namespace }}
  name: mariadb
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      namespace: default
      name: mariadb
      labels:
        app: mariadb
    spec:
      nodeSelector:
        {{ node_label }}: enabled
      # TODO(DTadrzak): it must be removed in future
      securityContext:
        runAsUser: 0
      containers:
        - name: mariadb
          image: {{ image }}
          imagePullPolicy: Always
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/start.sh"
            - name: DEPENDENCY_CONFIG
              value: "/tmp/start.sh,/etc/mysql/my.cnf"
          ports:
            - containerPort: {{ port }}
          readinessProbe:
            tcpSocket:
              port: {{ port }}
          volumeMounts:
            - name: startsh
              mountPath: /configmaps/start.sh
            - name: mycnf
              mountPath: /configmaps/my.cnf
            - name: mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: startsh
          configMap:
            name: mariadb-startsh
        - name: mycnf
          configMap:
            name: mariadb-mycnf
        - name: mysql
          emptyDir: {}
