apiVersion: v1
kind: ConfigMap
data:
  db-sync.sh: |-
    neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2-conf.ini upgrade a84ccf28f06a
    neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2-conf.ini upgrade 3d0e74aa7d37
