apiVersion: v1
kind: ConfigMap
data:
  openvswitch-vswitchd.sh: |+
    #!/bin/bash
    set -ex

    sleep 20

    modprobe openvswitch
    ovs-vsctl --no-wait show
    bash /tmp/openvswitch-ensure-configured.sh {{ neutron.bridge_name }} {{ network.minion_interface_name }}
    exec /usr/sbin/ovs-vswitchd unix:/run/openvswitch/db.sock --mlockall
