apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-mycnf
data:
  start.sh: |-
    [mysqld]
    bind-address=0.0.0.0
    port={{ mariadb_port }}

    binlog_format=ROW
    default-storage-engine=innodb
    innodb_autoinc_lock_mode=2

    datadir=/var/lib/mysql/

    wsrep_cluster_address=gcomm://
    wsrep_provider_options="gmcast.listen_addr=tcp://0.0.0.0:{{ mariadb_wsrep_port }};ist.recv_addr=0.0.0.0:{{ mariadb_ist_port }}"

    wsrep_node_address=0.0.0.0:{{ mariadb_wsrep_port }}
    wsrep_sst_receive_address=0.0.0.0:{{ mariadb_sst_port }}

    wsrep_provider=/usr/lib/galera/libgalera_smm.so
    wsrep_cluster_name="{{ mariadb_cluster_name }}"
    wsrep_node_name={{ mariadb_node_name }}
    wsrep_sst_method=xtrabackup-v2
    wsrep_sst_auth=root:{{ mariadb_password }}
    wsrep_slave_threads=4

    max_connections=1000

    [server]
    pid-file=/var/lib/mysql/mariadb.pid
